### ISSUE TITLE
Version 2.0.0 does not work, because of naming issue

### ISSUE THREAD

**Issue by jvitkauskas** [voxpupuli/puppet-iis#100]
Hi, we are trying to use version 2.0.0 of this module and noticed that one file was misnamed. This issue appears to be fixed, but no new version is available. Do you plan to release version with fix included?

Link to the fixing commit: https://github.com/voxpupuli/puppet-iis/commit/63a1c4a88ab6697c52097c32424f0e944029f387

**Comment by petems** [comment]
I think a 2.0.1 release is worth cutting, that's a live bug...

**Comment by nibalizer** [comment]
Agree

**Comment by nibalizer** [comment]
We released 2.0.2. 2.0.1 was tagged but not released because automation is hard.
