### ISSUE TITLE
manage_app_pool.pp SPECIFICUSER identity unless not executing properly

### ISSUE THREAD

**Issue by sysengkm** [voxpupuli/puppet-iis#104]
The SPECIFICUSER user section does not properly enclose the username and password in quotes and results in no change if the application pool identity is changed. This includes the current master and the v2.0.2 branch which downloads via "puppet module install puppet-iis"

Debug output results include, among a whole lot of other parsing errors,

> "You must provide a value expression following the '-ne' operator."

The exec section properly uses escaped double-quotes. The unless section does not.

Current code:
`
if(\$pool.processModel.userName -ne ${apppool_username}){exit 1;}if(\$pool.processModel.password -ne ${apppool_userpw}){exit 1;}exit 0;",`

The following changes resolve the issue:
`if(\$pool.processModel.userName -ne \"${apppool_username}\"){exit 1;}if(\$pool.processModel.password -ne \"${apppool_userpw}\"){exit 1;}exit 0;",`

**Comment by dirtdiver9** [comment]
I ran into this same issue.  Updating with the changes above solved it.

**Comment by petems** [comment]
@sysengkm Ok, looks like that should be an easy enough change.

Can you give me some example code that causes this issue so I can add an acceptance test?

**Comment by dirtdiver9** [comment]
Sorry it took me a bit.

This is what I was running:

    iis::manage_app_pool { 'application_app_pool':
      enable_32_bit           => false,
      managed_runtime_version => 'v4.0',
      apppool_identitytype    => 'SpecificUser',
      apppool_username        => 'domain\username',
      apppool_userpw          => 'password',
    }

**Comment by petems** [comment]
This has been fixed in 107, but I want to add an acceptance test for it also.

Plus we should probably have some rspec for this, opening #108
