### ISSUE TITLE
iis_version fact runs profile code

### ISSUE THREAD

**Issue by binford2k** [voxpupuli/puppet-iis#116]
If your `Desktop/WindowsPowerShell/profile.ps1` outputs any text, it will be included in the `iis_version` fact.

```
PS C:\Users\Administrator> facter -p iis_version
 _________
| boogers |
 ---------
\                             .       .
 \                           / `.   .' "
  \                  .---.  <    > <    >  .---.
   \                 |    \  \ - ~ ~ - /  /    |
         _____          ..-~             ~-..-~
        |     |   \~~~\.'                    `./~~~/
       ---------   \__/                        \__/
      .'  O    \     /               /       \  "
     (_____,    `._.'               |         }  \/~~~/
      `----.          /       }     |        /    \__/
            `-.      |       /      |       /      `. ,~~|
                ~-.__|      /_ - ~ ^|      /- _      `..-'
                     |     /        |     /     ~-.     `-. _  _  _
                     |_____|        |_____|         ~ - . _ _ _ _ _>
8.5
```

**Comment by petems** [comment]
I can't reproduce this, but maybe because I'm running the Powershell terminal as administrator...Can you do a quick gif of it in action? 

Hmm, this makes things a little sticky. Was going to say regex, but what if someone has an IIS-like number in their profile...

**Comment by binford2k** [comment]
Does your `profile.ps1` run when you log in? When you open a new PowerShell window, it should display.

Any time you run PowerShell non-interactively, you should include `-NoProfile` to prevent this. I'll toss up a quick PR to fix it.

**Comment by binford2k** [comment]
Ha. Never mind. It's been corrected already in https://github.com/voxpupuli/puppet-iis/commit/1ab7a8e36b010050912138ae1450c2771402ed05#diff-134c9abaaee49886d874c96362fd4c75. I was on an old version :-/

**Comment by ferventcoder** [comment]
This is awesome...
