### ISSUE TITLE
Update to use new 2.0.0 release of Windows feature module

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-iis#117]
- [ ] Update dependancy of voxpupuli-windowsfeature to use new type and provider release (Blocked on https://github.com/voxpupuli/puppet-windowsfeature/issues/48) 
- [ ] Change all `ensure_resource` to direct declarations of the type provider
- [ ] Update tests
- [ ] Run acceptance tests
- [ ] Tag and release

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
