### ISSUE TITLE
IIS No Sites Issue

### ISSUE THREAD

**Issue by stephenbawks** [voxpupuli/puppet-iis#128]
So I found an interesting issue.  If there are NO sites already on the server, on line 24:

gci "IIS:\sites" | %{ Get-ItemProperty $_.PSPath  | Select name, PhysicalPath, ApplicationPool, HostHeader, State, Bindings } | ConvertTo-Json -Depth 4 -Compress

That will obviously return zero results.  This creates a NULL value with no data and when I was trying to pull down a NEW site to the server with no sites currently on it, the code was failing because there was no data in the value that was being passed on and I was getting the following error.

Error: Failed to apply catalog: A JSON text must at least contain two octets!

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
