### ISSUE TITLE
Update the license?

### ISSUE THREAD

**Issue by ferventcoder** [voxpupuli/puppet-iis#130]
Is the LICENSE file still correct? It is still pointed to OpenTable, versus adding additional lines.

**Comment by ferventcoder** [comment]
@voxpupuli/collaborators ^^

**Comment by liamjbennett** [comment]
I have no concerns with the license being updated here if it needs to be. Although I no longer represent the views of OT on this any more so maybe @fessyfoo should provide confirmation.

**Comment by ferventcoder** [comment]
I was thinking the license may change here to say 

~~~sh
Copyright 2013-2015 OpenTable
Copyright 2015-2016 Vox Pupuli
~~~

But if OpenTable still holds the license for this, that's find as well.

**Comment by ferventcoder** [comment]
Also, pretty sure this existed in 2013

**Comment by igalic** [comment]
:+1:

**Comment by juniorsysadmin** [comment]
Note that the license in the metadata also went from MIT to Apache-2.0

**Comment by juniorsysadmin** [comment]
I recall having a similar situation with regard to the metadata in one of the other former OpenTable modules. We probably should create an issue for any inconsistent metadata <-> license mismatches in our modules as well.

**Comment by juniorsysadmin** [comment]
> Note that the license in the metadata also went from MIT to Apache-2.0

This happened after migration: https://github.com/voxpupuli/puppet-iis/commit/de2fb2a947c32338247c3656d9f46c7b8dc2ebec#diff-490694a9db8f7a371538da1abe484314

Pretty sure it's okay, given it was done by @liamjbennett

**Comment by juniorsysadmin** [comment]
> Copyright 2015-2016 Vox Pupuli

After brief discussions on IRC, I don't think we can do this just yet.

**Comment by juniorsysadmin** [comment]
> We probably should create an issue for any inconsistent metadata <-> license mismatches in our modules as well

Pull Requests have now been done for these

**Comment by ferventcoder** [comment]
My point here is similar to 

* https://github.com/puppetlabs/puppetlabs-dsc/blob/master/NOTICE / https://github.com/puppetlabs/puppetlabs-dsc/blob/master/README.md#license
* https://github.com/puppetlabs/puppetlabs-powershell/blob/master/NOTICE#L3-L4

Attributions are definitely required to be carried with Apache 2. Although I am not a lawyer.

**Comment by igalic** [comment]
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

> Must
> 
> Include Copyright
> 
> Describes whether the original copyright must be retained.

**Comment by alexjfisher** [comment]
This module has a lot of [contributors ](https://github.com/voxpupuli/puppet-iis/graphs/contributors); several of whom have made significant contributions.   Unless they were asked to assign copyright as a condition of having their PRs merged, my understanding is that they own the copyright on the code they committed and would have to be consulted before changing the licence under which their code is distributed.

My understanding is that the licence was changed to Apache 2 in metadata.json by mistake.  Is there any reason it couldn't be changed back to MIT?

**Comment by ferventcoder** [comment]
I wasn't stating that the license changed, more of whether the attributions were correct. It sounds like there are two issues here.

**Comment by ferventcoder** [comment]
@igalic looks like MIT requires the same - https://tldrlegal.com/license/mit-license

**Comment by juniorsysadmin** [comment]
LICENSE <-> metadata mismatches have been resolved by #135

**Comment by juniorsysadmin** [comment]
@ferventcoder My understanding is that we cannot legally do
```
Copyright 2015-2016 Vox Pupuli
```
just yet

**Comment by ferventcoder** [comment]
👍

**Comment by ferventcoder** [comment]
Just out of curiosity, how many contributions were taken in under the mistaken Apache 2 license?

**Comment by juniorsysadmin** [comment]
> Just out of curiosity, how many contributions were taken in under the mistaken Apache 2 license?

Quite a lot. (Of course bad metadata doesn't mean that those commits are licensed under Apache-2.0 if the LICENSE file said something else during that time)

**Comment by ferventcoder** [comment]
> Quite a lot. (Of course bad metadata doesn't mean that those commits are licensed under Apache-2.0 if the LICENSE file said something else during that time)

Ah, true. Just metadata.json file change. So not as bad as first thought. 👍

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
