### ISSUE TITLE
Unmanage spec_helper_acceptance.rb until it gets fixed in modulesync_config

### ISSUE THREAD

**Issue by bbriggs** [voxpupuli/puppet-iis#133]
The `spec_helper_acceptance.rb` template is currently missing from modulesync_config. The short term workaround seems to be to unmanage that file in `.sync.yml` until we can get it added back to modulesync.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
