### ISSUE TITLE
Missing site_id in iis_site

### ISSUE THREAD

**Issue by BarnumD** [voxpupuli/puppet-iis#141]
Missing site_id in version (proposed) 3.0.0 iis_site.  Not sure if it's just missing from the readme, or from the module's functionality.

**Comment by juniorsysadmin** [comment]
This doesn't seem to be in the module at the moment

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
