### ISSUE TITLE
Missing apppool_identitytype in iis_application

### ISSUE THREAD

**Issue by BarnumD** [voxpupuli/puppet-iis#142]
Missing apppool_identitytype  in version (proposed) 3.0.0 iis_application. Not sure if it's just missing from the readme, or from the module's functionality.

**Comment by juniorsysadmin** [comment]
Appears to be there https://github.com/voxpupuli/puppet-iis/blob/98087d79b24433e4988f71f9983aeb128de975a5/manifests/manage_app_pool.pp#L9 but not documented @BarnumD Feel free to make a PR to add this to the README :)

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
