### ISSUE TITLE
Manage authentication in iis_site

### ISSUE THREAD

**Issue by BarnumD** [voxpupuli/puppet-iis#143]
Add ability to manage the authentication section of an iis site (see image).  I would like the ability to ensure the 'anonymous authentication' is set to 'application pool identity'.  Note: this is a different setting than that of configuring the identity in the application pool.

<img src="http://origin-symwisedownload.symantec.com/library/BUSINESS/HOWTO83371/001-iis-default-web-site-authentication-setting.png">

**Comment by gigadafud** [comment]
Not sure if this is the same thing or not but I set Windows Authentication by setting it to Read/Write on the server itself.

    exec { 'check-feature-delegation':
      command   => 'Set-WebConfiguration //System.WebServer/Security/Authentication/windowsAuthentication -metadata overrideMode -value Allow -PSPath IIS:/',
      onlyif    => 'if ((get-WebConfiguration //System.WebServer/Security/Authentication/windowsAuthentication).overridemode -ne \'Allow\') { exit 0 }',
      provider  => powershell,
    }

**Comment by AlbMor** [comment]
Hi

Vote for this feature since we need to enable windows authentication for a site via puppet

Regards

Alberto

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
