### ISSUE TITLE
iis_application

### ISSUE THREAD

**Issue by stephenbawks** [voxpupuli/puppet-iis#146]
I am getting the following error when trying to create an iis_application:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'site' at /etc/puppetlabs/code/environments/ql_nonprod/site/profile/manifests/windows/iis/modulename.pp:62:5 on node nodename

I am passing the site name correctly but it just keeps blowing up on me here.  I am honestly not sure what I am doing wrong here.

**Comment by rrenshaw** [comment]
Site is now a reserved word with the introduction of Application Orchestration.  This module needs to be changed to use a different parameter.

**Comment by bpadakanti** [comment]
We are running into the same issue and it will be helpful, if we know when is the fix coming and when can we download the updated module.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
