### ISSUE TITLE
Error in IIS Site SpecificUser

### ISSUE THREAD

**Issue by scrothers** [voxpupuli/puppet-iis#148]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 2016
- Ruby: PE
- Distribution: PE EL7
- Module version: master
### How to reproduce (e.g Puppet code you use)

Try and set a specific user for IIS App Pool.
### What are you seeing

Error: Import-Module WebAdministration;$iis = New-Object Microsoft.Web.Administration.ServerManager;iis:;$pool = get-item IIS:\AppPools***_;$pool.processModel.username = "**__";$pool.processModel.password = "_**_";$pool.processModel.identityType = 3;$pool | set-item; returned 1 instead of one of [0] Error: /Stage[main]/Bsb::Websites::Cms/Iis::Manage_app_pool[**__]/Exec[app pool identitytype - *_**]/returns: change from notrun to 0 failed: Import-Module WebAdministration;$iis = New-Object Microsoft.Web.Administration.ServerManager;iis:;$pool = get-item IIS:\AppPools\****;$pool.processModel.username = "**_";$pool.processModel.password = "_***";$pool.processModel.identityType = 3;$pool | set-item; returned 1 instead of one of [0]
### What behaviour did you expect instead

Application Pool to go Into SpecificUser mode with AD user.
### Output log

See above.
### Any additional information you'd like to impart

I think I have a fix, I'm working on it in a fork.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
