### ISSUE TITLE
Changing Site Directory

### ISSUE THREAD

**Issue by JC1738** [voxpupuli/puppet-iis#15]
I updated the site and virtual site to point to new directories, after the puppet run, a new folder was created with the correct value, however looking at IIS the site and virtual directory were still pointing to the old folder.  I deleted the site and virtual directory from IIS and it correctly recreated them pointing to the new directory.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
