### ISSUE TITLE
enable_32_bit is not enabled when specified to be true

### ISSUE THREAD

**Issue by kevinjbeattie** [voxpupuli/puppet-iis#152]
I've noticed that the 32bit option is not enabled in the default app pool (or any other pool) when I specify a value of true.  What am I doing wrong?
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 4.5.2
- Ruby: 2.1.8
- Distribution: windows server 2008 r2 enterprise
- Module version: 1.4.1 (tried upgrading to the latest, but this broke dependencies on other modules)
### How to reproduce (e.g Puppet code you use)

Here is the puppet code I tested.  I have rebooted and also performed an 'iisreset' command but the 32bit application options is still false.

```
class iisdefaultpool {
      iis::manage_app_pool {'DefaultAppPool':
        ensure => 'present',
        enable_32_bit => true,
        managed_runtime_version => 'v2.0',
    }
}
include iisdefaultpool
```
### What are you seeing

When I check the "application pool defaults" the option for "enable 32-bit applications" is still false.  Rebooting or running an 'iisreset' command did not have any effect.
### What behaviour did you expect instead

I expected the option for "enable 32-bit applications" to be set to true.
### Output log

`C:\Users<username>\Desktop>puppet parser validate iispooldefaults.pp

C:\Users<username>\Desktop>puppet apply --debug iispooldefaults.pp
Debug: Runtime environment: puppet_version=4.5.2, ruby_version=2.1.8, run_mode=user, default_encodin
g=IBM437
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Loading external facts from C:/ProgramData/PuppetLabs/puppet/cache/facts.d
Info: Loading facts
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/chocolatey/lib
/facter/chocolateyversion.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/chocolatey/lib
/facter/choco_install_path.rb
Info: Loading facts
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/dsc/lib/facter
/powershell_version.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/dsc/lib/facter
/uses_win32console.rb
Info: Loading facts
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/iis/lib/facter
/iis_version.rb
Info: Loading facts
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/facter_dot_d.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/package_provider.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/pe_version.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/puppet_vardir.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/root_home.rb
Debug: Loading facts from C:/ProgramData/PuppetLabs/code/environments/staging/modules/stdlib/lib/fac
ter/service_provider.rb
Debug: Facter: fact "facterversion" has resolved to "3.2.0".
Debug: Facter: initializing WMI
Debug: Facter: searching "C:\ProgramData\PuppetLabs\facter\facts.d" for external facts.
Debug: Facter: searching "C:/ProgramData/PuppetLabs/puppet/cache/facts.d" for external facts.
Debug: Facter: no external facts were found.
Debug: Facter: setting fact "env_windows_installdir" based on the value of environment variable "FAC
TER_env_windows_installdir".
Debug: Facter: fact "env_windows_installdir" has resolved to "C:\Program Files\Puppet Labs\Puppet".
Debug: Facter: loading all custom facts.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\chocolatey\lib\facter.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
chocolatey\lib\facter\chocolateyversion.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
chocolatey\lib\facter\choco_install_path.rb.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\dsc\lib\facter.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
dsc\lib\facter\powershell_version.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
dsc\lib\facter\uses_win32console.rb.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\iis\lib\facter.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
iis\lib\facter\iis_version.rb.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\stdlib\lib\facter.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\facter_dot_d.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\package_provider.rb.
Debug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\pe_version.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\puppet_vardir.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\root_home.rb.
Info: Facter: loading custom facts from C:/ProgramData\PuppetLabs\code\environments\staging\modules\
stdlib\lib\facter\service_provider.rb.
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Facter: searching for custom fact "operatingsystem".
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\chocolatey\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\dsc\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\iis\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\stdlib\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\chocolatey\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\dsc\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\iis\lib\facter.
Debug: Facter: searching for operatingsystem.rb in C:/ProgramData\PuppetLabs\code\environments\stagi
ng\modules\stdlib\lib\facter.
Debug: Facter: resolving operating system facts.
Debug: Facter: resolving kernel facts.
Debug: Facter: fact "kernel" has resolved to "windows".
Debug: Facter: fact "kernelrelease" has resolved to "6.1.7601".
Debug: Facter: fact "kernelmajversion" has resolved to "6.1".
Debug: Facter: fact "kernelversion" has resolved to "6.1.7601".
Debug: Facter: fact "osfamily" has resolved to "windows".
Debug: Facter: fact "operatingsystemmajrelease" has resolved to "2008 R2".
Debug: Facter: fact "operatingsystemrelease" has resolved to "2008 R2".
Debug: Facter: fact "hardwaremodel" has resolved to "x86_64".
Debug: Facter: fact "architecture" has resolved to "x64".
Debug: Facter: fact "operatingsystem" has resolved to "windows".
Debug: Facter: fact "system32" has resolved to "C:\Windows\system32".
Debug: Facter: fact "os" has resolved to {
  architecture => "x64",
  family => "windows",
  hardware => "x86_64",
  name => "windows",
  release => {
    full => "2008 R2",
    major => "2008 R2"
  },
  windows => {
    system32 => "C:\Windows\system32"
  }
}.
Debug: Facter: searching for custom fact "osfamily".
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\chocolatey\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\dsc\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\iis\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\stdlib\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\chocolatey\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\dsc\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\iis\lib\facter.
Debug: Facter: searching for osfamily.rb in C:/ProgramData\PuppetLabs\code\environments\staging\modu
les\stdlib\lib\facter.
Debug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\chocolatey\lib\facter.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\dsc\lib\facter.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\iis\lib\facter.
Debug: Facter: searching for custom facts in C:/ProgramData\PuppetLabs\code\environments\staging\mod
ules\stdlib\lib\facter.
Debug: Facter: fact "agent_specified_environment" has resolved to "staging".
Debug: Facter: fact "choco_install_path" has resolved to "C:\ProgramData\chocolatey".
Debug: Facter: fact "chocolateyversion" has resolved to "0".
Debug: Facter: fact "iis_version" has resolved to "7.5
".
Debug: Facter: fact "puppetversion" has resolved to "4.5.2".
Debug: Facter: fact "pe_version" resolved to null and will not be added.
Debug: Facter: fact "is_pe" has resolved to false.
Debug: Puppet::Type::Package::ProviderChocolatey: file C:\ProgramData\chocolatey\bin\choco.exe does
not exist
Debug: Puppet::Type::Package::ProviderAix: file /usr/bin/lslpp does not exist
Debug: Puppet::Type::Package::ProviderDpkg: file /usr/bin/dpkg does not exist
Debug: Puppet::Type::Package::ProviderApt: file /usr/bin/apt-get does not exist
Debug: Puppet::Type::Package::ProviderAptitude: file /usr/bin/aptitude does not exist
Debug: Puppet::Type::Package::ProviderRpm: file rpm does not exist
Debug: Puppet::Type::Package::ProviderAptrpm: file apt-get does not exist
Debug: Puppet::Type::Package::ProviderSun: file /usr/bin/pkginfo does not exist
Debug: Puppet::Type::Package::ProviderYum: file yum does not exist
Debug: Puppet::Type::Package::ProviderDnf: file dnf does not exist
Debug: Puppet::Type::Package::ProviderFink: file /sw/bin/fink does not exist
Debug: Puppet::Type::Package::ProviderOpenbsd: file pkg_info does not exist
Debug: Puppet::Type::Package::ProviderFreebsd: file /usr/sbin/pkg_info does not exist
Debug: Puppet::Type::Package::ProviderHpux: file /usr/sbin/swinstall does not exist
Debug: Puppet::Type::Package::ProviderNim: file /usr/sbin/nimclient does not exist
Debug: Puppet::Type::Package::ProviderOpkg: file opkg does not exist
Debug: Puppet::Type::Package::ProviderPacman: file /usr/bin/pacman does not exist
Debug: Puppet::Type::Package::ProviderPkg: file /usr/bin/pkg does not exist
Debug: Puppet::Type::Package::ProviderPkgin: file pkgin does not exist
Debug: Puppet::Type::Package::ProviderPkgng: file /usr/local/sbin/pkg does not exist
Debug: Puppet::Type::Package::ProviderPortage: file /usr/bin/emerge does not exist
Debug: Puppet::Type::Package::ProviderPorts: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderPortupgrade: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderRug: file /usr/bin/rug does not exist
Debug: Puppet::Type::Package::ProviderSunfreeware: file pkg-get does not exist
Debug: Puppet::Type::Package::ProviderUp2date: file /usr/sbin/up2date-nox does not exist
Debug: Puppet::Type::Package::ProviderUrpmi: file urpmi does not exist
Debug: Puppet::Type::Package::ProviderZypper: file /usr/bin/zypper does not exist
Debug: /Package[dummy]: Provider windows does not support features virtual_packages; not managing at
tribute allow_virtual
Debug: Facter: fact "package_provider" has resolved to "windows".
Debug: Facter: fact "pe_major_version" resolved to null and will not be added.
Debug: Facter: fact "pe_minor_version" resolved to null and will not be added.
Debug: Facter: fact "pe_patch_version" resolved to null and will not be added.
Debug: Facter: fact "powershell_version" has resolved to "3.0".
Debug: Facter: fact "puppet_vardir" has resolved to "C:/ProgramData/PuppetLabs/puppet/cache".
Debug: Facter: fact "root_home" resolved to null and will not be added.
Debug: Puppet::Type::Service::ProviderBase: file kill does not exist
Debug: Puppet::Type::Service::ProviderDaemontools: file /usr/bin/svc does not exist
Debug: Puppet::Type::Service::ProviderDebian: file /usr/sbin/update-rc.d does not exist
Debug: Puppet::Type::Service::ProviderGentoo: file /sbin/rc-update does not exist
Debug: Puppet::Type::Service::ProviderLaunchd: file /bin/launchctl does not exist
Debug: Puppet::Type::Service::ProviderOpenbsd: file /usr/sbin/rcctl does not exist
Debug: Puppet::Type::Service::ProviderOpenrc: file /bin/rc-status does not exist
Debug: Puppet::Type::Service::ProviderRedhat: file /sbin/chkconfig does not exist
Debug: Puppet::Type::Service::ProviderRunit: file /usr/bin/sv does not exist
Debug: Puppet::Type::Service::ProviderSystemd: file systemctl does not exist
Debug: Puppet::Type::Service::ProviderUpstart: 0 confines (of 4) were true
Debug: Facter: fact "service_provider" has resolved to "windows".
Debug: Facter: fact "uses_win32console" resolved to null and will not be added.
Debug: Facter: resolving ruby facts.
Debug: Facter: fact "rubyplatform" has resolved to "x64-mingw32".
Debug: Facter: fact "rubysitedir" has resolved to "C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/
ruby/site_ruby/2.1.0".
Debug: Facter: fact "rubyversion" has resolved to "2.1.8".
Debug: Facter: fact "ruby" has resolved to {
  platform => "x64-mingw32",
  sitedir => "C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/site_ruby/2.1.0",
  version => "2.1.8"
}.
Debug: Facter: resolving path facts.
Debug: Facter: fact "path" has resolved to "C:\Program Files\Puppet Labs\Puppet\facter/bin;C:\Progra
m Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet Labs\Puppet\facter\bin;C:\Program File
s\Puppet Labs\Puppet\hiera\bin;C:\Program Files\Puppet Labs\Puppet\mcollective\bin;C:\Program Files\
Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin;C:\Program Files\Puppet Labs
\Puppet\sys\tools\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Puppe
t Labs\Puppet\bin;C:\Windows\System32\WindowsPowerShell\v1.0\".
Debug: Facter: resolving EC2 facts.
Debug: Facter: resolving virtualization facts.
Debug: Facter: fact "is_virtual" has resolved to true.
Debug: Facter: fact "virtual" has resolved to "vmware".
Debug: Facter: EC2 facts are unavailable: not running under an EC2 instance.
Debug: Facter: resolving GCE facts.
Debug: Facter: not running under a GCE instance.
Debug: Facter: resolving augeas facts.
Debug: Facter: executing command: augparse --version
Debug: Facter: augparse was not found on the PATH.
Debug: Facter: resolving id facts.
Debug: Facter: fact "id" has resolved to "<domain><username>".
Debug: Facter: fact "identity" has resolved to {
  user => "<domain><username>"
}.
Debug: Facter: resolving memory facts.
Debug: Facter: fact "memoryfree" has resolved to "6.91 GiB".
Debug: Facter: fact "memoryfree_mb" has resolved to 7080.14.
Debug: Facter: fact "memorysize" has resolved to "8.00 GiB".
Debug: Facter: fact "memorysize_mb" has resolved to 8191.49.
Debug: Facter: fact "memory" has resolved to {
  system => {
    available => "6.91 GiB",
    available_bytes => 7424065536,
    capacity => "13.57%",
    total => "8.00 GiB",
    total_bytes => 8589402112,
    used => "1.09 GiB",
    used_bytes => 1165336576
  }
}.
Debug: Facter: resolving networking facts.
Debug: Facter: initializing Winsock
Debug: Facter: fact "ipaddress_Local Area Connection" has resolved to "10.64.8.155".
Debug: Facter: fact "ipaddress" has resolved to "10.64.8.155".
Debug: Facter: fact "netmask_Local Area Connection" has resolved to "255.255.254.0".
Debug: Facter: fact "netmask" has resolved to "255.255.254.0".
Debug: Facter: fact "network_Local Area Connection" has resolved to "10.64.8.0".
Debug: Facter: fact "network" has resolved to "10.64.8.0".
Debug: Facter: fact "ipaddress6_Local Area Connection" has resolved to "fe80::8c1d:f408:661f:196b%11
".
Debug: Facter: fact "ipaddress6" has resolved to "fe80::8c1d:f408:661f:196b%11".
Debug: Facter: fact "netmask6_Local Area Connection" has resolved to "ffff:ffff:ffff:ffff::".
Debug: Facter: fact "netmask6" has resolved to "ffff:ffff:ffff:ffff::".
Debug: Facter: fact "network6_Local Area Connection" has resolved to "fe80::%11".
Debug: Facter: fact "network6" has resolved to "fe80::%11".
Debug: Facter: fact "macaddress_Local Area Connection" has resolved to "00:50:56:AC:11:D2".
Debug: Facter: fact "macaddress" has resolved to "00:50:56:AC:11:D2".
Debug: Facter: fact "mtu_Local Area Connection" has resolved to 1500.
Debug: Facter: fact "hostname" has resolved to "<hostname>".
Debug: Facter: fact "domain" has resolved to "<domain>".
Debug: Facter: fact "fqdn" has resolved to "<hostname>.<domain>".
Debug: Facter: fact "interfaces" has resolved to "Local Area Connection".
Debug: Facter: fact "networking" has resolved to {
  domain => "<domain>",
  fqdn => "<hostname>.<domain>",
  hostname => "<hostname>",
  interfaces => {
    Local Area Connection => {
      bindings => [
        {
          address => "<ip_address>",
          netmask => "255.255.254.0",
          network => "<network>"
        }
      ],
      bindings6 => [
        {
          address => "fe80::8c1d:f408:661f:196b%11",
          netmask => "ffff:ffff:ffff:ffff::",
          network => "fe80::%11"
        }
      ],
      ip => "<ip_address>",
      ip6 => "fe80::8c1d:f408:661f:196b%11",
      mac => "00:50:56:AC:11:D2",
      mtu => 1500,
      netmask => "255.255.254.0",
      netmask6 => "ffff:ffff:ffff:ffff::",
      network => "<network>",
      network6 => "fe80::%11"
    }
  },
  ip => "<ip_address>",
  ip6 => "fe80::8c1d:f408:661f:196b%11",
  mac => "00:50:56:AC:11:D2",
  mtu => 1500,
  netmask => "255.255.254.0",
  netmask6 => "ffff:ffff:ffff:ffff::",
  network => "<network>",
  network6 => "fe80::%11",
  primary => "Local Area Connection"
}.
Debug: Facter: resolving timezone facts.
Debug: Facter: fact "timezone" has resolved to "Pacific Daylight Time".
Debug: Facter: resolving desktop management interface facts.
Debug: Facter: fact "productname" has resolved to "VMware Virtual Platform".
Debug: Facter: fact "serialnumber" has resolved to "VMware-42 2c c2 8b f4 1c c6 6a-c6 22 24 9b 20 70
 e4 d9".
Debug: Facter: fact "manufacturer" has resolved to "Phoenix Technologies LTD".
Debug: Facter: fact "dmi" has resolved to {
  manufacturer => "Phoenix Technologies LTD",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 2c c2 8b f4 1c c6 6a-c6 22 24 9b 20 70 e4 d9"
  }
}.
Debug: Facter: resolving processor facts.
Debug: Facter: fact "hardwareisa" has resolved to "x64".
Debug: Facter: fact "processorcount" has resolved to 2.
Debug: Facter: fact "physicalprocessorcount" has resolved to 2.
Debug: Facter: fact "processor0" has resolved to "Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz".
Debug: Facter: fact "processor1" has resolved to "Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz".
Debug: Facter: fact "processors" has resolved to {
  count => 2,
  isa => "x64",
  models => [
    "Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz",
    "Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz"
  ],
  physicalcount => 2
}.
Debug: Facter: resolving uptime facts.
Debug: Facter: fact "uptime_seconds" has resolved to 8243.
Debug: Facter: fact "uptime_hours" has resolved to 2.
Debug: Facter: fact "uptime_days" has resolved to 0.
Debug: Facter: fact "uptime" has resolved to "2:17 hours".
Debug: Facter: fact "system_uptime" has resolved to {
  days => 0,
  hours => 2,
  seconds => 8243,
  uptime => "2:17 hours"
}.
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: importing 'C:/ProgramData/PuppetLabs/code/environments/staging/modules/iis/manifests/init.pp'
 in environment staging
Debug: importing 'C:/ProgramData/PuppetLabs/code/environments/staging/modules/iis/manifests/manage_a
pp_pool.pp' in environment staging
Debug: Automatically imported iis::manage_app_pool from iis/manage_app_pool into staging
Notice: Compiled catalog for <hostname>.<domain> in environment staging in 0.39 seconds
Debug: Puppet::Type::Exec::ProviderPosix: feature posix is missing
Debug: Puppet::Type::Exec::ProviderShell: feature posix is missing
Debug: Creating default schedules
Debug: Loaded state in 0.02 seconds
Debug: Loaded state in 0.03 seconds
Info: Applying configuration version '1471897139'
Debug: /Stage[main]/Iispooldefaults/Iis::Manage_app_pool[DefaultAppPool]/Exec[Framework-DefaultAppPo
ol]/require: subscribes to Exec[Create-DefaultAppPool]
Debug: /Stage[main]/Iispooldefaults/Iis::Manage_app_pool[DefaultAppPool]/Exec[32bit-DefaultAppPool]/
require: subscribes to Exec[Create-DefaultAppPool]
Debug: /Stage[main]/Iispooldefaults/Iis::Manage_app_pool[DefaultAppPool]/Exec[ManagedPipelineMode-De
faultAppPool]/require: subscribes to Exec[Create-DefaultAppPool]
Debug: Exec[Create-DefaultAppPool](provider=powershell): Executing check 'cmd.exe /c ""C:\Windows\sy
stem32\WindowsPowershell\v1.0\powershell.exe" -NoProfile -NonInteractive -NoLogo -ExecutionPolicy By
pass -Command - < "C:\Users<user>\AppData\Local\Temp\puppet-powershell20160822-2412-c1gjqh.ps1""'

Debug: Executing: 'cmd.exe /c ""C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfil
e -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - < "C:\Users<user>\AppData\Local\Temp
\puppet-powershell20160822-2412-c1gjqh.ps1""'
Debug: Exec[Framework-DefaultAppPool](provider=powershell): Executing check 'cmd.exe /c ""C:\Windows
\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfile -NonInteractive -NoLogo -ExecutionPolicy
 Bypass -Command - < "C:\Users<user>\AppData\Local\Temp\puppet-powershell20160822-2412-1q6y35s.ps
1""'
Debug: Executing: 'cmd.exe /c ""C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfil
e -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - < "C:\Users<user>\AppData\Local\Temp
\puppet-powershell20160822-2412-1q6y35s.ps1""'
Debug: Exec[32bit-DefaultAppPool](provider=powershell): Executing check 'cmd.exe /c ""C:\Windows\sys
tem32\WindowsPowershell\v1.0\powershell.exe" -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Byp
ass -Command - < "C:\Users<user>\AppData\Local\Temp\puppet-powershell20160822-2412-j6ok3u.ps1""'
Debug: Executing: 'cmd.exe /c ""C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfil
e -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - < "C:\Users<user>\AppData\Local\Temp
\puppet-powershell20160822-2412-j6ok3u.ps1""'
Debug: Exec[ManagedPipelineMode-DefaultAppPool](provider=powershell): Executing check 'cmd.exe /c ""
C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfile -NonInteractive -NoLogo -Execu
tionPolicy Bypass -Command - < "C:\Users<user>\AppData\Local\Temp\puppet-powershell20160822-2412-
im3e2q.ps1""'
Debug: Executing: 'cmd.exe /c ""C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -NoProfil
e -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - < "C:\Users<user>\AppData\Local\Temp
\puppet-powershell20160822-2412-im3e2q.ps1""'
Debug: Finishing transaction 55092360
Debug: Storing state
Debug: Stored state in 0.02 seconds
Notice: Applied catalog in 5.27 seconds
Debug: Applying settings catalog for sections reporting, metrics
Debug: Finishing transaction 51942960
Debug: Received report to process from <hostname>.<domain>
Debug: Evicting cache entry for environment 'staging'
Debug: Caching environment 'staging' (ttl = 0 sec)
Debug: Processing report from <hostname>.<domain> with processor Puppet::Reports::Store`
### Any additional information you'd like to impart

No.

**Comment by kevinjbeattie** [comment]
Thank you in advance for any help you can provide!

**Comment by kevinjbeattie** [comment]
Hmm, there may be more to it than just the puppet IIS module.  I was expecting the value to be true when trying to turn this on manually via PowerShell.

`PS C:\Windows\system32> Set-ItemProperty IIS:\apppools\DefaultAppPool -name "enable32BitAppOnWin64" -Value "true"
PS C:\Windows\system32> (Get-ItemProperty iis:\ -name applicationPoolDefaults.enable32BitAppOnWin64).Value
False`

**Comment by kevinjbeattie** [comment]
Hello,

OK, so this is actually working.  What I was looking at was the default permissions for the app pool, and what this value changes is the setting for the app pool itself.  It does enable it, just not the default value.  My bad.

Is there a way to change the default value with this module?

Thanks in advance.

-Kevin Beattie

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
