### ISSUE TITLE
Is there support on Powershell v2.0

### ISSUE THREAD

**Issue by urhs127** [voxpupuli/puppet-iis#154]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 3.4.0
- Ruby:
- Distribution:
- Module version:v2.0.0
### How to reproduce (e.g Puppet code you use)

Using Windows 2008 R2, powershell 2.0.
windowsfeature.pp
windowsfeature { 'MSMQ':
  ensure => present,
}
puppet apply windowsfeature.pp
### What are you seeing

Error: Could not prefetch windowsfeature provider 'default': Execution of 'C:\Windows\sysnative\WindowsPowershell\v1.0\powershell.exe Get-WindowsFeature | ConvertTo-JSON' returned 1: The term 'ConvertTo-JSON' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a pathwas included, verify that the path is correct and try again.
At line:1 char:36
- Get-WindowsFeature | ConvertTo-JSON <<<<
- CategoryInfo          : ObjectNotFound: (ConvertTo-JSON:String) [], Comm
  andNotFoundException
- FullyQualifiedErrorId : CommandNotFoundException
### What behaviour did you expect instead

Enable Windows feature

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
