### ISSUE TITLE
Managing Core IIS Functionality

### ISSUE THREAD

**Issue by bostrowski13** [voxpupuli/puppet-iis#155]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet:  4.5.2
- Ruby:  ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
- Distribution:  RHEL 7.x Master, Windows 2008, 2012+ clients
- Module version:  2.0.2

Hi,

Hoping this is the right place for this but is it possible to make a feature request?  We want to configure many settings for IIS that are stored in the applicationhost.config, including log location, logging at the site/server level, log fields, log rotation schedule, default document, request filtering, controlling http methods, and authentication mechanisms. We'd also like to set things like the machine key (which is actually stored in C:\Windows\Microsoft.NET\Framework64\v<FRAMEWORK_VERS>\Config\web.config).

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
