### ISSUE TITLE
iis::manage_app_pool support 'no managed runtime'

### ISSUE THREAD

**Issue by cfbarbero** [voxpupuli/puppet-iis#163]
We are using this module to manage IIS for some new dotnet core apps.  Dotnet core requires that the app pool is set to no managed code (https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configure-the-website-in-iis).  This is not supported in this module right now.

I'd like to be able to do something like this:
```
  iis::manage_app_pool { 'Website1'':
    enable_32_bit           =>  false,
    managed_runtime_version => '',
  }
```

**Comment by igalic** [comment]
we also have `iis_pool`, which has a `runtime` parameter, that also has to be a number.
both, the defined type and the native type translate this to PowerShell.

Do you know what the appropriate `managedRuntimeVersion` is in case of non-managed runtimes?

**Comment by cfbarbero** [comment]
Empty string.

The following PS will correctly set the runtime version
```
Import-Module WebAdministration; Set-ItemProperty "IIS:\AppPools\Website1" managedRuntimeVersion ''
```

**Comment by igalic** [comment]
oh. i didn't realize your initial report was already complete :D

**Comment by cfbarbero** [comment]
I have a [commit](https://github.com/DiceHoldingsInc/puppet-iis/tree/SupportNoManagedRuntime2.x) in a fork that I believe fixes this, however, I'm not sure what branch to submit it against.  The patch I have is based off of v2.0.2 which is the current forge version of this module.

**Comment by igalic** [comment]
generally, you should always submit against `master`

**Comment by igalic** [comment]
your patch looks good to me
however, i'd also patch up `iis_pool`, and add spec tests
and, well, documentation :D

**Comment by cfbarbero** [comment]
master is way different from 2.0.2.  It looks like it's got a bunch of changes for switching from resources to types.  In my brief testing, there were bugs running the master version.  I believe iis_pool is part of the new type structure that only exists in master.  Is master stable and do you plan to push a version of it to the forge?

I will update documentation.

I'm happy to add spec tests, however, i was getting an error running the spec tests in my branch.
```
cris@cris-Virtual-Machine:~/code/puppet-iis$ rake
rake aborted!
LoadError: cannot load such file -- puppet_blacksmith/rake_tasks
/home/cris/code/puppet-iis/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
