### ISSUE TITLE
IIS and PowerShell versions not compatible.

### ISSUE THREAD

**Issue by aroeber-kovarus** [voxpupuli/puppet-iis#165]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version:  puppet-iis (v2.0.2)

## How to reproduce (e.g Puppet code you use)
using Code Manager, Puppetfile
Have:
mod 'puppetlabs-powershell', :latest
mod 'puppet-iis', :latest

## What are you seeing

clear; puppet module list --environment development
Warning: Module 'puppetlabs-powershell' (v2.1.0) fails to meet some dependencies:
  'puppet-iis' (v2.0.2) requires 'puppetlabs-powershell' (>= 1.0.1 < 2.0.0)
/etc/puppetlabs/code/environments/development/modules
├── module-template (v0.0.1)
├── puppet-iis (v2.0.2)
├── puppetlabs-motd (v1.4.0)
├── puppetlabs-powershell (v2.1.0)  invalid
├── puppetlabs-registry (v1.1.3)
└── puppetlabs-stdlib (v4.13.1)

### ALSO:
Change Puppetfile to:
mod 'puppetlabs-powershell', '2.0.0'
mod 'puppet-iis', :latest
####
puppet module list --environment development
Warning: Module 'puppetlabs-powershell' (v2.0.0) fails to meet some dependencies:
  'puppet-iis' (v2.0.2) requires 'puppetlabs-powershell' (>= 1.0.1 < 2.0.0)
/etc/puppetlabs/code/environments/development/modules
├── module-template (v0.0.1)
├── puppet-iis (v2.0.2)
├── puppetlabs-motd (v1.4.0)
├── puppetlabs-powershell (v2.0.0)  invalid
├── puppetlabs-registry (v1.1.3)
└── puppetlabs-stdlib (v4.13.1)

## What behaviour did you expect instead
modules to show correctly in the process to allow them to work correctly, with no errors or warnings.
Also > puppetlabs-powershell (all versions) should not show as invalid.

## Any additional information you'd like to impart
Versions shown in the forge are:
mod 'puppetlabs-powershell', '2.1.0'
mod 'puppet-iis', '2.0.2'
Which match the version installed, via Code Manger and the latest call.

**Comment by aroeber-kovarus** [comment]
The working version is 1.0.6
/etc/puppetlabs/code/environments/development/modules
├── module-template (v0.0.1)
├── puppet-iis (v2.0.2)
├── puppetlabs-motd (v1.4.0)
├── puppetlabs-powershell (v1.0.6)
├── puppetlabs-registry (v1.1.3)
└── puppetlabs-stdlib (v4.13.1)

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
