### ISSUE TITLE
Are there plans to make this Puppet 4.x compatible?

### ISSUE THREAD

**Issue by existancenext** [voxpupuli/puppet-iis#169]
## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 4.8.0

Currently this module is not compatible with Puppet 4.x, which causes issues due to it being a dependency of a few other modules (including chocolatey/chocolatey_server)
Are there any plans to bring this to 4.x compatibility? 
I understand there are a few things to work through, but this would be great to see

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
