### ISSUE TITLE
manage_virtual_application does not update physical path in IIS

### ISSUE THREAD

**Issue by kevinkuszyk** [voxpupuli/puppet-iis#174]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.3.2
- Distribution: win x64
- Module version: 2.0.2

## How to reproduce (e.g Puppet code you use)

The following code will create a virtual application in IIS:

```
iis::manage_virtual_application {'foo':
    site_name   => 'Default Web Site',
    site_path   => "${baseDir}/foo",
    app_pool    => 'AppPool'
  }
```

Now change the change the `site_path` and re-run `puppet apply`.

## What are you seeing

On the second run the physical path in IIS is not updated with the new `site_path`.

## What behaviour did you expect instead

On the second run I was expecting the physical path in IIS to be changed to the new `site_path` value.

## Output log

```
Notice: Compiled catalog for icvd7x64ult72.foo.net in environment production in 1.03 seconds
Notice: Applied catalog in 69.52 seconds
```

## Any additional information you'd like to impart

I was expecting the virtual application site path to be updated like it is with websites.  I see the following in the output when I try to change the site path for a website:

```
Notice: Compiled catalog for icvd7x64ult72.foo.net in environment production in 0.90 seconds
Notice: /Stage[main]/Defaultwebsite/Iis::Manage_site[Default Web Site]/Exec[UpdateSite-PhysicalPath-Default Web Site]/returns: executed successfully
...
Notice: Applied catalog in 109.90 seconds
```

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
