### ISSUE TITLE
Unable to map site path to UNC

### ISSUE THREAD

**Issue by acl-oss** [voxpupuli/puppet-iis#182]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.4 
- Ruby: 2.0.0p648
- Distribution: RHEL7
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)
Adding a share path to a UNC location 

iis_site {$websitename:
    name        => $websitename,
    path        => $sitepath,
    port        => $port,
    ip          => $ipaddress,
    host_header => $websitename,
    app_pool    => $applicationpool,
   }

where $sitepath is defined in yaml as  sitepath: '\\foo.com\bar\aaa\bb\ccc\ddd'

## What are you seeing

Validate method failed for class path: File paths must be fully qualified, not sitepath: '\\foo.com\bar\aaa\bb\ccc\ddd'

## What behaviour did you expect instead
For it to map the UNC path to the sitepath
## Any additional information you'd like to impart
In the iis_site.rb there is this line 
raise("File paths must be fully qualified, not '#{value}'") unless value =~ %r{.:(\/|\\)} || value =~ %r{\/\/[^\/]+\/[^\/]+}
I'm not sure if the // regex is correct, should it be \\ (\\\\) ?

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
