### ISSUE TITLE
Manage log path

### ISSUE THREAD

**Issue by loulougunner** [voxpupuli/puppet-iis#187]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: 3.0.0

## What are you seeing
We have no way to configure the log repository of a site.

## What behaviour did you expect instead
It should be good to add a new attribute to iis_site, like logfile => "D:\logs\iis\site1\".

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
