### ISSUE TITLE
Unable to create virtual directories of the same name in different IIS sites with iis_virtualdirectory

### ISSUE THREAD

**Issue by mjlumetta** [voxpupuli/puppet-iis#188]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.4
- Ruby: 2.3.1
- Distribution: Windows 2012 R2 64-bit
- Module version: 3.0.0 (but would have been true back to 2.0.0)

## How to reproduce (e.g Puppet code you use)

We're updating our puppet-iis module to 3.0.0 and have run into a problem using `iis_virtualdirectory`. We have a series of IIS sites that share a Node project for the front end. Each site has a virtual directory named `static` from which assets are served. With 1.4.1, we were able to accomplish that with `iis::manage_virtual_directory`:

```
iis::manage_virtual_directory { "site1-static":
    path => /physical/asset/path,
    site_name => "site1",
    directory => "static"
}

iis::manage_virtual_directory { "site2-static":
    path => /physical/asset/path,
    site_name => "site2",
    directory => "static"
}
```

I tried to do the same with `iis_virtualdirectory`, but since the name parameter is also the name of the virtual directory, I get an error (see below). The new code I'm trying looks something like this:

```
iis_virtualdirectory { "site1-static":
    name => "static",
    path => /physical/asset/path,
    site => "site1"
}

iis_virtualdirectory { "site2-static":
    name => "static",
    path => /physical/asset/path,
    site => "site2"
}
```

## What are you seeing

Running `puppet apply` gives the following error:

```
Error: Puppet::Parser::AST::Resource failed with error 
ArgumentError: Cannot alias Iis_virtualdirectory[intranet.project.local-static] to ["static"] at C:/MyProject/Build/modules/project/manifests/iis/intranet.pp:44; 
resource ["Iis_virtualdirectory", "static"] already declared at C:/MyProject/Build/modules/project/manifests/iis/web.pp:34 at C:/MyProject/Build/modules/project/manifests/iis/intranet.pp:44 on node <buildmachine>.<domain>.com
```

## What behaviour did you expect instead

I would expect either to be able to override the namevar with a directory name, like in the old `iis::manage_virtual_directory`, or I would expect the resource type to use multiple namevars so that virtual directories can be unique by directory name and site.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
