### ISSUE TITLE
Looking for inforamtion on version 4.0.0, 

### ISSUE THREAD

**Issue by raman1236** [voxpupuli/puppet-iis#193]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing
We have seen IIS version 4.0.0 till 08/06/2017, suddenly now it disappears and the module is rolled back to IIS 3.0.0 it seems, we are updated from IIS module version 3.0.0 to 4.0.0. I am very curies to know the reason behind the roll back and how do it effect the current users for IIS module version 4.0.0

**Comment by bastelfreak** [comment]
This is a bit confusing, sorry. This module here got adopted by Puppetlabs, they provide a version 4:
https://forge.puppet.com/puppetlabs/iis

Puppetlabs renamed itself to Puppet, but their forge namespace is still puppet: https://forge.puppet.com/puppetlabs

Vox Pupuli owns the puppet namespace at the forge: https://forge.puppet.com/puppet

In the near future we want to migrate this whole module + repo to Puppet(Labs). @hunner do you have more information about this?
