### ISSUE TITLE
SSL certficate not getting renew on my IIS-8

### ISSUE THREAD

**Issue by BalamuruganMariyappan** [voxpupuli/puppet-iis#196]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:3.7.5
- Ruby:
- Distribution:Windows IIS8
- Module version:

Hi Team,

 We are using our puppet module only to manage in IIS in our environment, and we are using below hiera variable to store the ssl certificate.

iis::cert::file::XXX: wildcard.XXX.com.pfx
iis::cert::thumbprint::XXX: AABBBCCCDDEESSSAAAAQQQ

Now our XXX.com SSL certificate is going to expire soon, so I renew that certificate and converted in .pfx format and upload in repo and the same i modified the thumbprint value for the new certificate.

Ran puppet /redeploy the application after that code is merged with my master repo. But that certificate is not getting replicated to my IIS server.(still, it's using my old certificate which is going to expire).. Could you please advise, here what will be the issue.

Note: The new ssl certificate file and thumbprint got updated in my puppet master, but it's not coming to my IIS server.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
