### ISSUE TITLE
SSL Certificate binding doesn't work unless C:/Temp directory is present

### ISSUE THREAD

**Issue by kensykora** [voxpupuli/puppet-iis#33]
Provisioning an IIS site with a binding against a VM that does not have a directory called C:\temp\ throws errors when creating an SSL binding using this module. Module should use the standard Windows Temp directory (`$env:TEMP`) instead of an arbitrary C:\temp directory.

Here are the errors thrown when you try to run this manifest:

``` puppet
  iis::manage_app_pool {"${applicationName}": ensure => present }

  iis::manage_site { $applicationName:
    ensure      => present,
    site_path   => "${webPath}", #Must be \\'s for IIS to work correctly
    app_pool    => "${applicationName}",
    host_header => "${hostHeader}",
    require     => File['application-root'],
  }

  acl { 'iis_root':
    target => "${webPath}",
    inherit_parent_permissions => true,
    permissions => [
      { identity => 'IIS_IUSRS', rights => ['full'] },
      { identity => 'IUSR', rights => ['read'] },
      { identity => 'vagrant', rights => ['full'] }
    ],
    require => File['application-root'],
  }

  iis::manage_binding { "${applicationName}-https":
    ensure => present,
    site_name => $applicationName,
    protocol => 'https',
    port => 443,
    host_header => $hostHeader,
    certificate_thumbprint => '‎########',
  }
```

Error:

```
==> default: Error: Could not set 'present' on ensure: No such file or directory - C:/temp/create-mysite.local-https.ps120140812-1688-4j4xak.lock at 42:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
==> default: 
==> default: Error: Could not set 'present' on ensure: No such file or directory - C:/temp/create-mysite.local-https.ps120140812-1688-4j4xak.lock at 42:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
==> default: Wrapped exception:
==> default: No such file or directory - C:/temp/create-mysite.local-https.ps120140812-1688-4j4xak.lock
==> default: Error: /Stage[main]/Application_server/Iis::Manage_binding[mysite.local-https]/File[create-mysite.local-https-certificate.ps1]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - C:/temp/create-mysite.local-https.ps120140812-1688-4j4xak.lock at 42:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
==> default: Error: Could not set 'present' on ensure: No such file or directory - C:/temp/inspect-mysite.local-https.ps120140812-1688-1vnygg2.lock at 36:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
==> default: 
==> default: Error: Could not set 'present' on ensure: No such file or directory - C:/temp/inspect-mysite.local-https.ps120140812-1688-1vnygg2.lock at 36:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
==> default: Wrapped exception:
==> default: No such file or directory - C:/temp/inspect-mysite.local-https.ps120140812-1688-1vnygg2.lock
==> default: Error: /Stage[main]/Application_server/Iis::Manage_binding[mysite.local-https]/File[inspect-mysite.local-https-certificate.ps1]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - C:/temp/inspect-mysite.local-https.ps120140812-1688-1vnygg2.lock at 36:C:/tmp/vagrant-puppet-4/modules-0/iis/manifests/manage_binding.pp
```

**Comment by karmafeast** [comment]
never put a 'space' character in the resource name for iis::manage_binding if is SSL - puppet won't be able to see the generated files it puts in c:\temp.

what you'll get is an SSL binding that has 'nothing selected' showing in IIS but it'll report that there is a binding on 443...

puppet will then run clean on subsequent runs.

you'll see it have errors finding the generated powershell in c:\temp if there's a space in the name if you run agent --debug.

i get that that it's a longer block of powershell in the exec for ensuring a binding on ssl but I'd rather see this all done in line instead of being put to particular loc of file system (that's not where puppet places micropowershell its going to run normally).

serious question, can you split a string over multiple lines in puppet code??? that would make powershell blocks in line without pulling them out into artifacts we deliver as scripts to run via templates a lot more sane.

**Comment by YarNhoj** [comment]
So I just ran into this same problem. It looks like the c:\temp path is hard coded into the manage_binding.pp.

```
    file { "inspect-${title}-certificate.ps1":
        ensure  => present,
        path    => "C:\\temp\\inspect-${name}.ps1",
        content => template('iis/inspect-certificate-binding.ps1.erb'),
      }

```

On my server 2k12 install that directory doesn't exist therefore puppet blows up. There is no provision to create that temp directory if it's not already there. So two ideas.

A. We enforce the creation of that directory if it doesn't exist.
B. We declare a variable temp_dir and make it required.

**Comment by igalic** [comment]
@kensykora what about the `$env:TEMP` option?

**Comment by petems** [comment]
We don't actually need to make the files on disk at all, and skip this problem completely. 

I think the whole thing could be simplified to this:

```puppet
exec { "Attach-Certificate-${title}":
        command   => template('iis/create-certificate-binding.ps1.erb'),
        onlyif    => template('iis/inspect-certificate-binding.ps1.erb'),
        provider  => powershell,
        logoutput => true,
      }
```

Then we dont need to worry about the temp directory at all 👍

**Comment by petems** [comment]
@YarNhoj @kensykora @karmafeast: can you try testing the SSL code with https://github.com/voxpupuli/puppet-iis/tree/manage_binding_to_templates? This shouldn't require a temp file directory at all.

If not, can someone give an example of what the code would look like, with a self-signed cert or something for an acceptance test?

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
