### ISSUE TITLE
Error thrown if trying to create sub-application second time

### ISSUE THREAD

**Issue by TheSpy** [voxpupuli/puppet-iis#52]
having this configuration

class iis {
  $adminSiteName = hiera('sites::admin::name')

  iis::manage_app_pool { 'admin':
    enable_32_bit           => false,
    managed_runtime_version => 'v4.0',
  }

  iis::manage_app_pool { 'position':
    enable_32_bit           => false,
    managed_runtime_version => 'v4.0',
  }

  iis::manage_site { $adminSiteName:
    site_path   => 'D:\sites\admin\current',
    port        => '80',
    ip_address  => '*',
    host_header => $adminSiteName,
    app_pool    => 'admin'
  }

  iis::manage_virtual_application { 'position':
    site_name => $adminSiteName,
    site_path => 'D:\sites\position\current',
    app_pool  => 'position'
  }

  iis::manage_virtual_application { 'position/api':
    site_name => $adminSiteName,
    site_path => 'D:\sites\position-api\current',
    app_pool  => 'position'
  }
}

and running the script two times:
First time the app is created correctly, 

-site
--position
---api

The second time it throws an error "Destination element already exist, please use force."
Seems like  in this case the sub-aps onlyif script does not work correctly.

![image](https://cloud.githubusercontent.com/assets/514031/7336494/9b8d9ae2-ec09-11e4-9775-df60f1931ec5.png)

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
