### ISSUE TITLE
[Question]Add support to hiera.

### ISSUE THREAD

**Issue by israelriibeiro** [voxpupuli/puppet-iis#60]
I managed to add hiera support. I want you, if it's possible, for someone to look at it. I'll add test. I test on controlled environment, but i'll add beaker to this. I test also in windows server 2012. 
Am i on the right path?

https://github.com/israelriibeiro/puppet-iis/blob/master/manifests/iis_hiera.pp

**Comment by liamjbennett** [comment]
This is interesting. I would love to know the use-case here. Are you just trying to manage a lot of sites?

I would have said something like this might belong in a profile rather than the module itself.

**Comment by israelriibeiro** [comment]
Hi, Liam.

yes, that's the case - i used this module to create many sites or pool as i want. I think it's easier to use this way. What do you mean by profile?

**Comment by liamjbennett** [comment]
I meant profile as in "roles and profiles" -http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/

**Comment by israelriibeiro** [comment]
Hi, Liam. 

I read Gary's article.  I find it quite useful to installed everything i need when i'm talking about cleaned machines, for example, i have hostgroup on foreman to install all php-stack to run a wordpress. Or, as i was talking to a friend of mine, this would be more useful to docker container. Could you clarify how my approach here fits into roles and profiles?   

Thanks for the article, i really apreciated.

**Comment by liamjbennett** [comment]
Well what you have created here is almost a profile already.

Your code's purpose is to install multiple sites/bindings on the one node. The arguments that you pass to may differ on a role by role basis therefore it's a profile or a the very minimum part of a internal module in your own codebase.

**Comment by colutti** [comment]
@israelriibeiro Could you please provide an example of how to use your hiera class in the default.yaml file? Where do I put your class at?

**Comment by israelriibeiro** [comment]
@colutti , if i correctly remember, i add this to node manifest:
```
class { "iis::iis_hiera": }
``` 
Maybe you could add this to hiera too:
```
classes
 - iis::iis_hiera
```

**Comment by colutti** [comment]
Yes, but how do you pass parameters to the class iis::iis_hiera?

**Comment by israelriibeiro** [comment]
@colutti , i described that here: https://github.com/israelriibeiro/puppet-iis#hiera

**Comment by colutti** [comment]
Thank you very much.

**Comment by colutti** [comment]
It would be nice to improve your documentation if you could add an example of how to add { 'iis::iis_hiera': } to the manifest, just to make sure everyone gets it.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
