### ISSUE TITLE
parameters should be formatted on unique lines

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-iis#63]
This is just a style guide issue where the parameters some of the classes/defines should be on their own lines.

example: https://github.com/puppet-community/puppet-iis/blob/master/manifests/manage_binding.pp#L2

The style guide suggests have each parameter on its own line:
https://docs.puppetlabs.com/guides/style_guide.html#display-order-of-parameters

**Comment by igalic** [comment]
how come travis isn't failing on this?
we're linting by default, so it should be…

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
