### ISSUE TITLE
Issue managing net.tcp , net.pipe, netmsmq, and msmq.formatname bindings. 

### ISSUE THREAD

**Issue by DoctahPopp871** [voxpupuli/puppet-iis#68]
The manage_binding.pp file defers to managing iis bindings by using the New-Webbinding cmdlet. However if you attempt to manage the binding types referenced above using this cmdlets you will not get the desired results. 

For example if you have a net.tcp binding With Binding Information of 808:\* You could create a resource definition like this : 

``` puppet
iis::manage_binding { 'webapi_site_binding2': 
    ensure       => 'present',
    site_name    => "webapi",
    protocol     => "net.tcp",
    port         => "808",
    ip_address   => '*',
    require      => true,
  }
```

However this would produce a binding of `net.tcp *:808`, rather than `net.tcp 808:*` . Mitigation would be to use the New-ItemProperty cmdlet for these binding types. 

```
New-ItemProperty -Path "IIS:\sites\sitename" \
  -Name Bindings -value @{protocol="net.tcp"; bindingInformation="808:*"}
```

Going to create some logic in the existing manage_binding.pp file to do this, unless there is already work underway, OR if there is a way to resolve this difference in binding using the New-Webbinding cmdlet.

**Comment by igalic** [comment]
i'm utterly confuzzled as to what `808:*` even means

**Comment by DoctahPopp871** [comment]
ip address:port:host 

Any request coming in over port 808 route to any hostname. I know TCP does not tag hostname values (which might be why you are "confuzzled")  this is a standard port binding for WAS or WCF implementations. Some articles on it out there.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
