### ISSUE TITLE
replace doubly escaped \ with simple /

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-iis#71]
as noted in https://github.com/voxpupuli/puppet-iis/pull/70#issuecomment-168729974

> Powershell will permit Foo:/bar/baz instead of Foo:\bar\baz.

Since @brushwood24 was making an addition it was just stayed with the current style to keep it consistent.

We should update our code to this easier to read for humans, we should replace doubly escaped backslashes (`\`) with simple forward slashes (`/`).

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
