### ISSUE TITLE
iis::manage_app_pool resource ordering

### ISSUE THREAD

**Issue by drmarconi** [voxpupuli/puppet-iis#86]
There is no resource ordering on certain parameters in in iis::manage_app_pool define type - for example setting the app pool max processes value. Puppet sometimes tries to apply this setting before the app pool has been created.

Adding 'require => Exec["Create-${app_pool_name}"],' to the "App Pool Max Processes - ${app_pool_name}" exec should fix. The same would need adding to other app pool configuration options that require the application pool to be created.

Thanks

**Comment by petems** [comment]
Closed via https://github.com/voxpupuli/puppet-iis/pull/90
