### ISSUE TITLE
Travis CI builds fail - due to --no-80chars-check

### ISSUE THREAD

**Issue by AviIsraeli** [voxpupuli/puppet-iis#91]
Maybe consider changing to --no-140chars-check ?

Thanks!

**Comment by jyaworski** [comment]
We need to modulesync again @igalic. :/

**Comment by igalic** [comment]
@jyaworski should we make modulesync_config → auto-pr?

**Comment by jyaworski** [comment]
@igalic @petems we need to actually add better Windows support to modulesync.... this is a mess in .sync.yml.

**Comment by igalic** [comment]
i nominate @petems as chief window cleanupper

**Comment by jyaworski** [comment]
I think this is solved. I see that 140 is in the Rakefile.
